# Generated by Django 3.0.8 on 2020-10-09 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201007_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMethod',
            fields=[
                ('send_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=15, verbose_name='Label of Send Method')),
                ('price', models.PositiveIntegerField(verbose_name='Send Method Price')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='send_method_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Send Method Price of Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='send_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.SendMethod'),
        ),
    ]
