# Generated by Django 3.0.8 on 2020-10-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201009_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmethod',
            name='alternative_price_text',
            field=models.CharField(null=True, blank=True, max_length=15, verbose_name='Text Alternative For Price'),
            preserve_default=False,
        ),
    ]
