# Generated by Django 3.0.8 on 2020-10-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sendmethod_alternative_price_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmethod',
            name='alternative_price_text',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Text Alternative For Price'),
        ),
    ]
