# Generated by Django 3.0.8 on 2020-10-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201012_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='parameter_type',
            new_name='order_status',
        ),
    ]
