# Generated by Django 3.0.8 on 2020-10-13 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201013_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='zibalpayment',
            name='transaction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='zibalPayments', to='core.Transaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PE', 'Pending'), ('AP', 'Approved')], default='PE', max_length=2),
        ),
    ]
