# Generated by Django 3.0.8 on 2020-08-14 13:19

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200813_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Model Code'),
        ),
        migrations.AlterField(
            model_name='model',
            name='image',
            field=models.ImageField(upload_to=core.models.get_upload_path_models),
        ),
        migrations.AlterField(
            model_name='model',
            name='in_stock',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='# In Stock'),
        ),
        migrations.AlterField(
            model_name='model',
            name='is_active',
            field=models.BooleanField(blank=True, default=1, null=True, verbose_name='Activation Status'),
        ),
    ]
