# Generated by Django 3.0.8 on 2020-10-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201013_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Transaction Date/Time'),
        ),
    ]
