# Generated by Django 3.0.8 on 2020-08-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200814_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Model Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='Product Code'),
        ),
    ]
