# Generated by Django 3.0.8 on 2020-10-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201013_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zibalpayment',
            name='status',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Zibal Payment Status'),
        ),
    ]
