# Generated by Django 3.0.8 on 2020-10-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201013_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expired',
            field=models.BooleanField(default=False, verbose_name='Is this Transaction expired?'),
        ),
    ]
