# Generated by Django 3.0.8 on 2020-08-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200817_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Receiver Phone Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_address',
            field=models.TextField(max_length=255, verbose_name='Receiver Postal Address'),
        ),
    ]
