# Generated by Django 3.0.8 on 2020-08-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200817_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='models',
            field=models.ManyToManyField(related_name='orders', to='core.Model'),
        ),
    ]
