# Generated by Django 3.0.8 on 2020-10-19 14:04

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201017_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflinePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Offline Payment Amount')),
                ('attachment', models.ImageField(upload_to=core.utils.get_upload_path_offline_payments)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offlinePayments', to='core.Transaction')),
            ],
        ),
    ]
