# Generated by Django 3.0.8 on 2020-08-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_order_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(default='3438B69E57', max_length=10, unique=True, verbose_name='Tracking Code'),
        ),
    ]
