# Generated by Django 3.0.8 on 2020-08-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200817_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, default='8395EE851D', max_length=10, unique=True, verbose_name='Tracking Code'),
        ),
    ]
