# Generated by Django 3.0.8 on 2020-10-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20201019_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='zibalpayment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
