# Generated by Django 3.0.8 on 2020-08-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200817_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Tracking Code'),
        ),
    ]
