# Generated by Django 3.0.8 on 2020-10-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_order_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='card_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Source Cart'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Transaction Description'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ref_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Transaction Reference Number'),
        ),
    ]
