# Generated by Django 3.0.8 on 2020-08-26 13:06

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200823_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cover',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=core.utils.get_upload_path_categories),
        ),
    ]
