# Generated by Django 3.0.8 on 2020-09-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200906_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='main_category',
            new_name='is_main_category',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='parameter_categories',
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table='product_cateogory',
        ),
    ]
