# Generated by Django 3.0.8 on 2021-01-15 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20201104_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, verbose_name='City Name')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, verbose_name='Province Name')),
            ],
        ),
        migrations.CreateModel(
            name='CitySendMethod',
            fields=[
                ('city_send_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.City')),
                ('send_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SendMethod')),
            ],
            options={
                'verbose_name_plural': 'City Send Methods',
                'db_table': 'core_city_send_method',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.Province'),
        ),
    ]
