# Generated by Django 3.0.8 on 2020-09-07 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200907_1523'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productcategory',
            table='core_product_cateogory',
        ),
    ]
