# Generated by Django 3.0.8 on 2021-01-16 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20210115_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='تهران', max_length=64, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.City'),
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.CharField(default='تهران', max_length=64, verbose_name='Province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='province_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.Province'),
        ),
        migrations.AddField(
            model_name='order',
            name='send_method_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.SendMethod'),
        ),
        migrations.AlterField(
            model_name='order',
            name='send_method',
            field=models.CharField(default='قبلی ها', max_length=64, verbose_name='Send Method'),
            preserve_default=False,
        ),
    ]
