# Generated by Django 3.0.8 on 2020-09-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200907_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='code',
            field=models.CharField(max_length=32, verbose_name='Model Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(error_messages={'unique': 'محصولی با این کد وجود دارد.'}, max_length=32, unique=True, verbose_name='Product Code'),
        ),
    ]
