# Generated by Django 3.0.8 on 2021-01-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210116_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='province_id',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='send_method_id',
            new_name='send_method',
        ),
    ]
