# Generated by Django 3.0.8 on 2021-01-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20210116_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='send_method_name',
            new_name='send_method_label',
        ),
    ]
