# Generated by Django 3.0.8 on 2021-01-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20210116_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Receiver Phone Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_address',
            field=models.TextField(blank=True, max_length=255, verbose_name='Receiver Postal Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=15, verbose_name='Receiver Postal Code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='province_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Province'),
        ),
    ]
