# Generated by Django 3.0.8 on 2021-01-19 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20210119_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('ZB', 'Zibal'), ('BM', 'Behpardakht Mellat'), ('OF', 'Offline.'), ('HA', 'Havaleh Anbar')], default='OF', max_length=2),
        ),
        migrations.CreateModel(
            name='HavalehAnbar',
            fields=[
                ('havaleh_anbar_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(verbose_name='Havaleh Anbar Amount')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='havalehAnbars', to='core.Transaction')),
            ],
        ),
    ]
