# Generated by Django 3.0.8 on 2021-01-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20210119_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='havalehanbar',
            name='delivered_by',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Havaleh Delivered By'),
        ),
        migrations.AddField(
            model_name='havalehanbar',
            name='requested_by',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Havaleh Requested By'),
        ),
    ]
