# Generated by Django 3.0.8 on 2021-01-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20210119_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_stage',
            field=models.CharField(choices=[('SBMT', 'Submitted'), ('INVC', 'Invoice Issued'), ('PACK', 'Packed'), ('POST', 'Sent by Post'), ('CRIR', 'Sent by Courier'), ('TRCK', 'Send Tracking Code Registered'), ('DLVR', 'Delivered')], default='SBMT', max_length=4),
        ),
        migrations.AddField(
            model_name='order',
            name='send_tracking_code',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Send Tracking Code'),
        ),
    ]
