# Generated by Django 3.0.8 on 2021-01-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(blank=True, default=1, null=True, verbose_name='Activation Status'),
        ),
    ]
